name: kohi_manager
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  connectivity_plus: ^7.0.0
  flutter_svg: ^2.2.1
  intl: ^0.20.2
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.3
  equatable: ^2.0.7
  url_launcher: ^6.3.2
  toastification: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4
  intl_utils: ^2.8.10
  build_runner: ^2.5.4


flutter:
  generate: true
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: ArFont
      fonts:
        - asset: assets/fonts/ar/static/Cairo-Regular.ttf
